### ISSUE TITLE
Stratholme: Balnazzar

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#120]
Human form works properly and uses all spells
But when goes into phase 2 dreadlord form...
Does not cast -
Shadowbolt Volley
Fear
Mind Blast

**Comment by Cillez** [comment]
@dreadnought101  Did you test solo or with more than 1 member?

**Comment by AvatarRoku112** [comment]
@Cillez we tested with a full group of players.

**Comment by Cillez** [comment]
Description:
Doesn't use all spells he is supposed to. 
Current behaviour:
When Grand Crusader Dathrohan transforms into Balnazzar in Stratholme, he doesn't use Shadowbolt Volley, fear or mind blast

Expected behaviour Please include links to your source (for ex. wowhead.com):
When he turns into Balnazzar, he should use shadowbolt volley, fear and mind blast.

Steps to reproduce the problem:
1. Go to strathome, and then to The Crimson Throne. http://www.wowhead.com/npc=10813/balnazzar
2. Attack Grand Crusader Dathrohan until he transform into balnazzar (40%)
3. Watch as balnazzar only does melee damage.

Useful links (ex; youtube.com): 
https://www.youtube.com/watch?v=z5rKlqX81fk (bad quality, from 2006. But you can see he uses fear)
https://classicdb.ch/?npc=10813#abilities

**Comment by BanjeeWoW** [comment]
Balnazzar also has very little movespeed, not sure if its normal, but a tank can more or less just walk away from him

**Comment by RenegadeWoW-CrazyJ** [comment]
This encounter has been reworked, and will be available with the next build.
