### ISSUE TITLE
Scarlet Monastery - Cathedral

### ISSUE THREAD

**Issue by Naberius** [renegadewow/Renegade-WoW#226]
**Description:**
SM - Cathedral, last part (church), inside area, all mobs inside are linked and pulling one pulls all

**Current behaviour:**
Upon opening the doors to the church aka last part of the dungeon (inside area) where Morgraine/Whitemane are and pulling a single mob, every enpc in the whole church gets tagged and aggros.

**Expected behaviour Please include links to your source (for ex. wowhead.com):**
Packs inside shouldn't be linked, bosses included.

**Steps to reproduce the problem:**
1. Open the doors to the last part of SM - Cath and aggro one of the mobs, very easy to reproduce

**Useful links (ex; youtube.com):** 
/

**Comment by renegadewow** [comment]
Resolved, will be applied on next restart.

**Comment by atticstatic** [comment]
Expected behaviour Please include links to your source (for ex. wowhead.com):
Packs inside shouldn't be linked, **bosses included.** 
^ This is not accurate information. Aggroing the Morg\white is suppose to pull everything in the building part (except the hidden torch boss). Mobs can run into other mobs and aggro them when low on hp. You can say what you want about it but I lived in sm for years I kid u not. Its **always** been that way in retail and on every other PS i've played on. I like how it was "confirmed" and will be fixed on restart. Prove it! At anytime I'd be happy to confirm my claims as well. >.> Sweet now a rogue or druid can solo the last boss without a single fight...gj guys!
