### ISSUE TITLE
More city guards...

### ISSUE THREAD

**Issue by dreadnought101** [renegadewow/Renegade-WoW#77]
Shield of Velen - lvl 80
Honor Guard - lvl 80
Kor'kron Elite - lvl 80
Kor'kron Overseer - lvl 75

Thief Catcher Farmountain - lvl 80
Huntress Skymane - lvl 80
Huntress Leafrunner - lvl 80
Huntress Ravenoak - lvl 80
Sentinel Stillbough - lvl 75
Officer Brady - lvl 80
General Marcus Jonathan - lvl 72
Hunter Sagewind - lvl 80
Scout Stronghand - lvl 80

**Comment by Cillez** [comment]
Most of these are fixed on test realm. Going through the list and checking the levels of guards to be sure.

**Comment by Cillez** [comment]
All are resolved on test realm. We recommend to wait with reporting more guards until we push the guard levels to live PTR, otherwise ticket will be closed. Will be pushed to main realm sometime next week. We still need to make sure every guard is correct level. We are not prioritizing this issues right now, which is why it takes time.
