### ISSUE TITLE
Sheath of Light [Retribution Paladin Talent]

### ISSUE THREAD

**Issue by Jaxsonmage** [renegadewow/Renegade-WoW#95]
When you do critical healing with Flash of Light or Holy Light, Sheath of Light HoT buff is suppose to stack with spell power. 

When I do a Flash of Light crit 1208 - it healing HoT would be 40 each tick, right now it is just 9. 

https://db.rising-gods.de/?spell=53503#see-also

**Comment by Animalthug** [comment]
Retribution - Sheath of Light 3/3
Increases your spell power by an amount equal to **30%** of your **attack power** and your critical healing spells heal the target for **60%** of the **healed amount** over 12 seconds.

Does not stack with spell power.

Re-test with correct math and attributes, then report back.

**Comment by Juckiey** [comment]
Sheath of Light scaling is fine right now. The only problem with it is a weird interaction with overhealing. If a player is missing 300hp, and you crit flash heal on them the sheath of light will be calculated with the 300 heal instead of the full flash heal. This also means that sheath of light doesnt heal for anything if you crit heal a player with full HP. 

Cant find any video/thread saying that it should work like this.

**Comment by Cillez** [comment]
Resolved.
